---
title: "For almen praksis"
subtitle: "Tilmelding og materialer"
---
📌 Hop til: [📋 Tilmelding](#tilmelding) | [❓ FAQ](#faq) | [💻 E-læring](#e-læring) | [📂 Materialer](#materialer)

### Om projektet
Projektet afprøver en enkel indsats, hvor tarmkræftscreening systematisk indgår i årskontrollen for patienter med type 2-diabetes.
Indsatsen består af en kort, struktureret samtale, der kan gennemføres på under 2 minutter i konsultationen.

Indsatsen består af tre enkle trin:

-	Spørg, om patienten har deltaget i tarmkræftscreening.

-	Rådgiv kort om øget risiko ved type 2-diabetes og mulighed for screening.

-	Bestil prøvetagningssæt online. Sættet sendes direkte til patientens adresse.

Læs mere om projektet, samarbejdspartnere og metode her: [Om projektet](om-projektet.qmd)  

### Honorar 
Klinikken honoreres for projektaktiviteter; honoraret er specificeret i samarbejdsaftalen, der fremsendes ved tilmelding.

## 📋 Tilmelding
Projektet henvender sig til almen praksis i Region Midtjylland og forventes at starte i september 2026 og have en varrighed på 6-9 måneder.

Når I tilmelder jeres klinik, registreres I som interesserede. Pladserne fordeles efter først-til-mølle-princippet. Senest tre hverdage efter tilmelding vil I modtage yderligere information om projektet samt en samarbejdsaftale, inden det endelige samarbejde aftales.

Ved at udfylde formularen accepterer I, at vi behandler jeres oplysninger i projektet. Oplysningerne bruges udelukkende til at registrere tilmeldinger og kontakte jer efterfølgende.  
Tilmeldingen er først registreret, når I har trykket på "Tilmeld" og modtager beskeden: "Tak for din tilmelding".

Udfyld tilmeldingsformularen herunder for at tilmelde jeres lægepraksis:

<iframe title="Tilmeldingsformular" src="https://redcap.link/spoerg-aarsstatus" width="100%" height="1000px" style="border: 6px solid black"> </iframe>


## ❓FAQ 
### Typiske spørgsmål

<details> <summary><strong>Er tilmelding bindende?</strong></summary> 
Nej. Tilmelding er i første omgang uforpligtende. Den endelige deltagelse aftales ved indgåelse af samarbejdsaftale. </details> 

<details> <summary><strong>Hvornår starter projektet?</strong></summary> 
Projektet forventes at starte i september 2026 og vare i 6-9 måneder. 

Efter en kort elektronisk oplæring kan klinikken begynde at spørge patienter og registrere svar. Ved spørgsmål eller tvivl kan klinikken kontakte projektkoordinator Tina Quist.

📧 tina.quist\@rm.dk  

☎️ 24 34 63 47 </details> 

<details> <summary><strong>Hvilke patienter kan indgå?</strong></summary> 
Projektet omfatter patienter med type 2-diabetes, som er i målgruppen for det nationale screeningsprogram for tarmkræft. Det vil sige patienter i alderen 51-74 år</details>

 <details> <summary><strong>Hvor meget tid skal vi bruge på projektet?</strong></summary> 
Relevante medarbejdere gennemfører en kort elektronisk oplæring med et forventet tidsforbrug på ca. 15 minutter. Samtalen kan gennemføres på under 2 minutter pr. patient og er tilrettelagt, så den kan integreres i eksisterende arbejdsgange. Indhentning af samtykke forventes at tage yderligere ca. 2 minutter. Alle medarbejdere i klinikken kan gennemføre interventionen og den kan fx implementeres ved prøvetagning forud for årsstatus. </details> 

<details> <summary><strong>Hvordan registreres patienterne?</strong></summary> 
Registrering af patienternes udsagn sker via en enkel onlineformular. </details>

<details> <summary><strong>Hvordan indhentes samtykke fra patienterne?</strong></summary> 
Som en del af samtalen informeres patienten om projektets formål, hvilke oplysninger der videregives, og hvordan oplysningerne anvendes til forskning.

Patienten gives mundtlig information og der udleveres en skriftlig information og en samtykkeerklæring, som gennemgås og underskrives.  
Samtykket omfatter: 

 - videregivelse af relevante oplysninger fra almen praksis til Afdeling for Folkeundersøgelser, og 

 - anvendelse af de videregivne oplysninger til forskningsformål i overensstemmelse med sundhedslovens § 10.

Deltagelse er frivillig, og patienten kan til enhver tid trække sit samtykke tilbage uden betydning for den øvrige behandling.

Klinikken noterer samtykke til videregiveelse af oplysninger i patientjournalen og opbevarer skriftlige samtykkeerklæringer, indtil projektet afsluttes og de indsamles af Steno Diabetes Center Aarhus. 

 </details>

 <details> <summary><strong>Hvordan håndteres data og patientoplysninger?</strong></summary>
Projektet gennemføres i overensstemmelse med gældende regler om databeskyttelse og sundhedslovgivning.  
Der indsamles kun de nødvendige oplysninger, og alle data behandles fortroligt og sikkert.
</details>

 <details> <summary><strong>Er der andre opgaver i almen praksis?</strong></summary>
Ved projektets afslutning indsender klinikken ti nøgletal:

- Antal patienter i målgruppen (Type 2-diabetes, 51-74 år)
- Antal patienter i målgruppen med gennemført årskontrol i projektperioden

Enkelte klinikker inviteres til at deltage i et kort opfølgende interview (ekstra honorar)
</details>

## 💻 E-læring
- **[Instruktionsvideo]{{< video "https://vimeo.com/1189887106" >}}**: Se videoen ved at trykke på linket.
- **[Skriftligt materiale](/images/Oplæringsmateriale_Tarmkræftscreening som del af årsstatus for diabetes.pdf)**: Kan bruges alene eller som supplement til videoen. 

## 📂 Materialer
Herunder finder du relevante materialer:

- **[Lommekort](/images/Lommekort.pdf)**: Trin-for-trin vejledning til procedurer i projektet.
- **[Patientinformation](/images/Patientinformation og samtykke_pilot.pdf)**: Information som udleveres til alle patienter, der registres i projektet. 
